version: '3'
services:
  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      # - vm.overcommit_memory=1 # Not support vm namespace
      - net.core.somaxconn=1024
      - net.ipv4.tcp_max_syn_backlog=1024

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter:v1.45.0
    ports:
      - 9121:9121
    command: --redis.addr=redis://redis:6379 --redis.password=redispass
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'
    depends_on:
      - redis

volumes:
  redis_data: