version: '3.8'
services:
  prometheus:
      image: prom/prometheus
      ports:
        - 9090:9090
      # links:
      #   - alertmanager:alertmanager
      volumes:
        - ./prometheus/:/etc/prometheus/
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      restart: always
      networks: 
        - monitoring

  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./prometheus/alertmanager/:/etc/alertmanager/
  #   restart: always
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   networks: 
  #     - monitoring

  grafana:
      image: grafana/grafana:7.4.3-ubuntu
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
      env_file:
        - ./grafana/config.monitoring
      environment:
        GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      restart: always
      networks: 
        - monitoring

  pushgateway:
      image: prom/pushgateway:latest
      restart: always
      ports:
          - 9091:9091
      networks: 
        - monitoring

networks:
  monitoring:

volumes:
    prometheus_data: {}
    grafana_data: {}