version: '3'
services:
  registry:
    container_name: registry
    restart: always
    image: registry:2.8.0
    ports:
     - "5000:5000"
    environment:
      # REGISTRY_HTTP_HOST: 
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/client.cert
      REGISTRY_HTTP_TLS_KEY: /certs/client.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE: s3
      REGISTRY_STORAGE_S3_BUCKET: 
      REGISTRY_STORAGE_S3_ACCESSKEY: 
      REGISTRY_STORAGE_S3_SECRETKEY: 
      REGISTRY_STORAGE_S3_REGION: ap-northeast-2
    volumes:
     - ./certs:/certs
     - ./auth:/auth