version: '3'
services:
    pushgateway:
        container_name: pushgateway
        image: prom/pushgateway:latest
        restart: always
        ports:
            - 9091:9091
    pushgateway-ttl:
        container_name: pushgateway-ttl
        image: dmathai/prom-pushgateway-ttl:latest
        restart: always
        ports:
            - 9092:9091
        command:
            - '--metric.timetolive=60s'