version: '3.8'
services:
  mosquitto:
    container_name: mosquitto
    image: 'eclipse-mosquitto:2.0.10'
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data/
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwd:/mosquitto/config/passwd
      - ./log/:/mosquitto/log/
    restart: always

volumes:
  mosquitto_data: {}