version: '3.8'
services:
  mosquitto:
    image: 'eclipse-mosquitto:2.0.7'
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data/
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwd.txt:/mosquitto/config/passwd.txt
      - ./log/:/mosquitto/log/
    # restart: always

volumes:
  mosquitto_data: {}